# Generated by Django 3.0.10 on 2020-09-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_arts',
            field=models.BooleanField(blank=True, default=0, verbose_name='Arts'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_drinks',
            field=models.BooleanField(blank=True, default=0, verbose_name='Drinks'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_env',
            field=models.BooleanField(blank=True, default=0, verbose_name='Env'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_games',
            field=models.BooleanField(blank=True, default=0, verbose_name='Games'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_photography',
            field=models.BooleanField(blank=True, default=0, verbose_name='Photography'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_social',
            field=models.BooleanField(blank=True, default=0, verbose_name='Social'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_sports',
            field=models.BooleanField(blank=True, default=0, verbose_name='Sports'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_startups',
            field=models.BooleanField(blank=True, default=0, verbose_name='Startups'),
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(choices=[('V', 'VIRTUAL'), ('P', 'PHYSICAL')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(choices=[('L', 'LUNCH'), ('WD', 'WEEKDAY'), ('WE', 'WEEKEND')], default='WD', max_length=2),
        ),
    ]
